# analytics-v1 - ReportGrid analytics service (v1)
#
#

description "analytics-v1 - ReportGrid analytics service (v1)"

start on runlevel [2345]
stop on runlevel [06]

respawn

pre-start script
  [ -d /var/run/reportgrid ] || install -m 755 -o reportgrid -g reportgrid -d /var/run/reportgrid
end script

script
  ulimit -n 65535
  if [ -f /etc/default/analytics-v1 ]; then . /etc/default/analytics-v1; fi
  su reportgrid -s "/bin/bash" -c "/usr/bin/java $JAVA_OPTS -Dakka.config=/etc/reportgrid/akka.conf -Dlogback.configurationFile=/etc/reportgrid/analytics-v1.logging.xml -jar /usr/share/java/analytics-v1.jar --configFile /etc/reportgrid/analytics-v1.conf >> /var/log/reportgrid/analytics-v1.stdout.log 2>&1"
end script

post-start script
  echo `status analytics-v1 | egrep -o '[0-9]+$' | head -n1` > /var/run/reportgrid/analytics-v1.pid
end script
